### ISSUE TITLE
Disable Rollback

### ISSUE THREAD

**Issue by smiLLe** [alexmercerind/safe_local_storage#1]
Hi :) I just found this package and i like it. However i don't need the Rollback Support and it seams like i am unable to just disable the feature. Do you plan on supporting this?

**Comment by smiLLe** [comment]
It creates up to 10 files which i don't want/need.

**Comment by alexmercerind** [comment]
I don't think would be any point of using this package then. It's used in my project(s). 😅 Why not just write to a simple file?

**Comment by smiLLe** [comment]
Well.... i agree haha. Thanks for the fast reply
